### ISSUE TITLE
Fail to cache

### ISSUE THREAD

**Issue by pedronveloso** [koush/UrlImageViewHelper#13]
I'm using the latest sources from NIO branch, and sometimes I get this:

08-27 13:13:31.324: ERROR/AndroidRuntime(5972): FATAL EXCEPTION: main
        java.lang.NullPointerException: key == null || value == null
        at android.util.LruCache.put(LruCache.java:167)
        at com.koushikdutta.urlimageviewhelper.UrlLruCache.put(UrlLruCache.java:9)
        at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper$2.run(UrlImageViewHelper.java:287)
        at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper$4$1.onPostExecute(UrlImageViewHelper.java:396)
        at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper$4$1.onPostExecute(UrlImageViewHelper.java:350)
        at android.os.AsyncTask.finish(AsyncTask.java:631)
        at android.os.AsyncTask.access$600(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4928)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by pedronveloso** [comment]
Actually just found out what is causing the crash, you see URL's with "blank" spaces are valid but must be converted before fetch.

For example, this URL will fail on UrlImageViewHelper but open OK in a browser:

http://www.exit.pt/webmm/exit/upload/88666 - Portugal Luso Grande Hotel do Luso (3) exterior.jpg

(copy-paste it as a whole, github will stop at the numbers)

Will submit a pull request fixing this

**Comment by koush** [comment]
Oh, don't use the NIO branch. That stuff was just for testing a NIO http client I was writing. I'll remove that branch.
Use master, that has the latest stuff now.

Please let me if the problem persists.

If you're interested in the NIO http client, you can now find it here:
https://github.com/koush/AndroidAsync

**Comment by koush** [comment]
Ok, I just confirmed this problem also exists on the master branch. WOrking on a fix now.

**Comment by koush** [comment]
Hi, this is not a a bug in the library. This is expected behavior with URL and getInputStream. Your URL has spaces in it, so it is an invalid url. Firefox/Chrome have behavior that takes invalid URLs and attempts to clean them up. Android's URI parsers do not have that same behavior.

Reference:
http://stackoverflow.com/questions/5818684/downloading-image-from-url-with-spaces-in-the-path-in-android

Here's what your URL _should_ look like when properly escaped:

http://www.exit.pt/webmm/exit/upload/88666%20-%20Portugal%20Luso%20Grande%20Hotel%20do%20Luso%20(3)%20exterior.jpg

So make sure wherever you are getting the image URls from is returning proper values.

Also, the "master" branch does not experience the crash you are seeing, so there should be no issue there either.

**Comment by pedronveloso** [comment]
Well, I've fixed by doing this:

String parsedURL = url.replaceAll(" ","%20");

I know it is not a proper URL, but in my case the error comes from the web-service itself so I've found it easier to parse on a lib level so that way I don't have to parse everywhere before sending to UrlImageViewHelper. I understand if you don't want to include this 'Browser-like" behavior by default.

Thanks for the AndroidAsync link ;)

**Comment by koush** [comment]
@pedronveloso Yep, that fix will work.

Though, keep in mind there are a whole host of other characters that may need proper escaping in the url path.
