### ISSUE TITLE
Error not found class UrlImageViewHelper

### ISSUE THREAD

**Issue by nookbone** [koush/UrlImageViewHelper#86]
Hi,
I use  'com.koushikdutta.urlimageviewhelper:urlimageviewhelper:1.0.4'
And i update my Build Tools Version to : 23.0.2

and i got error when i use class  UrlImageViewHelper

java.lang.NoClassDefFoundError: com.koushikdutta.urlimageviewhelper.UrlImageViewHelper
11-10 08:30:07.787 10742-10742/com.newproject E/AndroidRuntime:     at com.nookbone.MainSiteInActivity.onCreate(MainSiteInActivity.java:75)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5231)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:135)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
11-10 08:30:07.787 10742-10742/com.newproject  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
11-10 08:30:07.787 10742-10742/com.newproject E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

and this is my code : 

UrlImageViewHelper.setUrlDrawable(_ImageView, getResources().getString(R.string.Url) + _UserImages.GetUserEntity().DefaultPic, R.drawable.loadphotos);

Thanks for your help.

**Comment by nookbone** [comment]
?
